; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = adafruit_feather_esp32s3
framework = arduino
monitor_speed = 115200
lib_deps = 
	painlessmesh/painlessMesh@^1.5.4
	bblanchon/ArduinoJson @ ^6.21.4
monitor_dtr = 0
monitor_rts = 0
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
